version: '2'

networks:
  main:

services:
    haproxy:
        image: haproxy
        ports:
            - "9001:9000"
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        networks:
            - main
        depends_on:
          - clickhouse1
          - clickhouse2
          - clickhouse3


    zoo1:
        image: zookeeper:3.6.2
        expose:
            - "2181"
            - "2888"
            - "3888"
        environment:
            ZOO_MY_ID: "1"
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
            JVMFLAGS: -Dzookeeper.forceSync=no
            ZOO_4LW_COMMANDS_WHITELIST: "*"
        networks:
            - main

    zoo2:
        image: zookeeper:3.6.2
        expose:
            - "2181"
            - "2888"
            - "3888"
        environment:
            ZOO_MY_ID: "2"
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
            JVMFLAGS: -Dzookeeper.forceSync=no
            ZOO_4LW_COMMANDS_WHITELIST: "*"
        networks:
            - main

    zoo3:
        image: zookeeper:3.6.2
        expose:
            - "2181"
            - "2888"
            - "3888"
        environment:
            ZOO_MY_ID: "3"
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
            JVMFLAGS: -Dzookeeper.forceSync=no
            ZOO_4LW_COMMANDS_WHITELIST: "*"
        networks:
            - main

    clickhouse1:
        image: yandex/clickhouse-server
        restart: always
        ports:
            - "9101:9000"
        expose:
          #replica sync port
          - "9010"
          #client port
          - "9000"
        depends_on:
          - zoo1
          - zoo2
          - zoo3
        volumes:
          - ./config_1.xml:/etc/clickhouse-server/config.xml
        networks:
            - main

    clickhouse2:
        image: yandex/clickhouse-server
        restart: always
        ports:
            - "9102:9000"
        expose:
          #replica sync port
          - "9011"
          #client port
          - "9000"
        depends_on:
          - zoo1
          - zoo2
          - zoo3
        volumes:
          - ./config_2.xml:/etc/clickhouse-server/config.xml
        networks:
            - main

    clickhouse3:
        image: yandex/clickhouse-server
        restart: always
        ports:
            - "9103:9000"
        expose:
          #replica sync port
          - "9012"
          #client port
          - "9000"
        depends_on:
          - zoo1
          - zoo2
          - zoo3
        volumes:
          - ./config_3.xml:/etc/clickhouse-server/config.xml
        networks:
            - main
